Class staff.model.GetEmployeeResponse Extends %Persistent
{

Storage Default
{
<Data name="GetEmployeeResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^staff.model.GetEmployeeEC81D</DataLocation>
<DefaultData>GetEmployeeResponseDefaultData</DefaultData>
<IdLocation>^staff.model.GetEmployeeEC81D</IdLocation>
<IndexLocation>^staff.model.GetEmployeeEC81I</IndexLocation>
<StreamLocation>^staff.model.GetEmployeeEC81S</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
