Class staff.model.GetEmployeesResponse Extends %Persistent
{

Storage Default
{
<Data name="GetEmployeesResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^staff.model.GetEmployee4247D</DataLocation>
<DefaultData>GetEmployeesResponseDefaultData</DefaultData>
<IdLocation>^staff.model.GetEmployee4247D</IdLocation>
<IndexLocation>^staff.model.GetEmployee4247I</IndexLocation>
<StreamLocation>^staff.model.GetEmployee4247S</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
